<?$Vulns = new Vulns()?>
<?foreach ($this->paginator as $vulnRow):?>
    <?$vuln = $Vulns->get($vulnRow['id'])?>
    <!--Item Begin--->
    <div class="project clear" id="vulnRow<?=$vuln['id']?>">
        <div class="<?=$this->risks[$vuln['risk_level_id']]?> status"></div>
        <div class="clear info-block">
            <table class="vulnsRowTable">
                <tr>
                    <td class="vulnsRowTableName">
                        <a id="vulnLink<?=$vuln['id']?>" href="#vuln-view-<?=$vuln['id']?>" class="tittle">
                            [<?=$this->translate($this->types[$vuln['vuln_type_id']])?>] <?=$vuln['name']?>
                        </a>
                    </td>
                    <td class="vulnsRowTableLink">
                        <a href="<?=$vuln['exploit_link']?>" target="_blank"><?=$vuln['exploit_link']?></a>
                    </td>
                    <?if (strlen($vuln['description']) > Zend_Registry::get('config')->str_tables_limits->comments):?>
                        <td class="vulnsRowTableComment" title="<?=htmlspecialchars($vuln['description'], ENT_QUOTES)?>">
                            <?=mb_substr($vuln['description'], 0, Zend_Registry::get('config')->str_tables_limits->comments)?>...
                        </td>
                    <?else:?>
                        <td class="vulnsRowTableComment">
                            <?=$vuln['description']?>
                        </td>
                    <?endif?>                    
                </tr>
            </table>
        </div>
        <div class="ico-block clear">
            <a id="editVuln<?=$vuln['id']?>" class="icon-edit icon change" href="#" onclick="openVulnEditForm(<?=$vuln['id']?>);return false;">
                <p><?=$this->translate('L_CHANGE');?><span></span></p>
            </a>
        </div>
        <a id="deleteVuln<?=$vuln['id']?>" class="icon-cross icon close" onclick="vulnDelete(<?=$vuln['id']?>, '<?=$vuln['name']?>');return false;"></a>
    </div>
    <!--Item End--->
    
<?endforeach;?>
<? if ($this->paginator && $this->paginator->getPages()->pageCount > 1): ?>
    <?=$this->paginationControl($this->paginator)?>
<?endif?>
