<div id="top-fix" class="clear">
    <form id="filterForm" action="" method="post">
        <div id="top-m" class="clear">
            <div class="left">
                <label><?=$this->translate('L_FILTER')?></label>
                <input id="filterSearch" name="search" value="" title="" type="text" />
                <img id="searchIcon" src="/images/zoom.png" class="searchIcon cursor" onclick="goVulnsListLink(1);"/>
            </div>
            <div class="right">
                <a id="addVulnLink" href="#" data-type="" data-object="" class="button newicons2" title="<?=$this->translate('L_ADD_VULN')?>" onclick="openVulnAddForm($(this).data('type'), $(this).data('object'));return false;">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </a>
            </div>
        </div>
        <div id="middle" class="clear">
            <div>
                <label><?=$this->translate('L_VULN_TYPE')?></label>
                <select id="filterType" name="type" onchange="vulnsFilterTypeChange(this.value)">
                    <option value="0">-------</option>
                    <option value="web-app"><?=$this->translate('L_WEB_APPS');?></option>
                    <option value="server-software"><?=$this->translate('L_SPO');?></option>
                </select>
            </div>
            <div>
                <label><?=$this->translate('L_PARENT')?></label>
                <select id="filterParent" name="parent" onchange="vulnsFilterParentChange(this.value)">
                    <option value="0">-------</option>
                </select>
            </div>
            <div>
                <label><?=$this->translate('L_OBJECT')?></label>
                <select id="filterObject" name="object_id" onchange="vulnsFilterObjectChange(this.value);;if (!app_navigation) {goVulnsListLink(1)}">
                    <option value="0">-------</option>
                </select>
            </div>
        </div>
</div><!--End #top-fix-->

<div id="content">



</div><!--End #work-space #content-->

<script>
    function changePage(page) {
        vulnsListFilter(page)
    }
    (function($){
        //vulnsListFilter(1)
    })(jQuery);
</script>

