<section id="index-content" class="clear">
    <fieldset>
        <legend><?=$this->translate('L_LAST_PROJECTS')?></legend>
    </fieldset>

    <? foreach ($this->projects as $project):?>
        <!--Item Begin--->
        <div class="project clear" id="projectInView<?=$project['id']?>">
            <div class="clear info-block">
                <a href="/projects/view/project_id/<?=$project['id']?>" class="tittle"><?=$project['name']?></a>
                <p class="info"><?=nl2br(htmlspecialchars($project['comment']))?></p>
            </div>
            <div class="ico-block clear">
                <!--a class="icon-doc icon report" href="#report"><p>Отчет<span></span></p></a-->
                <a class="icon-edit icon change" href="#" id="projectEdit<?=$project['id']?>" onclick="openProjectEditForm(<?=$project['id']?>)"><p><?=$this->translate('L_CHANGE');?><span></span></p></a>
                <!--a class="icon-dload icon download" href="#"><p>Скачать<span></span></p></a-->
            </div>
            <a class="icon-cross icon close" id="projectDel<?=$project->id?>" onclick="projectDelete(<?=$project->id?>, '<?=$project->name?>')"></a>
        </div>
        <!--Item End--->
    <?endforeach?>

</section>

<!--------Mobal--------->
<div style="text-align: left;" class="remodal" data-remodal-id="modal">
    <button data-remodal-action="close" class="remodal-close float:right"></button>
    <h2><?=$this->translate('L_HASHES_LOAD_PAGE')?></h2>
    <p><?=$this->translate('L_HASHES_LOAD_DESC')?></p>

    <div class="form-container">
        <form class="form" method="post" action="/projects/hashes-load/" enctype="multipart/form-data" id="pairsForm">
            <div id="field2-container" class="field f_100 clear">
                <label for="field2">
                    <?=$this->translate('L_HASHES_LOAD_LIST_TYPE')?>
                </label>

                <div class="select clear">
                    <select name="list_type" id="pairsForm_type">
                        <option value="0"><?=$this->translate('L_HASHES_LOAD_LIST_TYPE_HASH_PASS')?></option>
                        <option value="1"><?=$this->translate('L_HASHES_LOAD_LIST_TYPE_HASH_PASS_SALT')?></option>
                    </select>
                </div>
            </div>
            <div id="field2-container" class="field f_100 clear">
                <label for="field2">
                    <?=$this->translate('L_HASHES_LOAD_LIST_ALG')?>
                </label>

                <div class="select clear">
                    <select name="alg">
                        <?foreach ((new HashAlgs())->getList() as $algId => $algName):?>
                            <option value="<?=$algId?>"><?=$algName?></option>
                        <?endforeach;?>
                    </select>
                </div>
            </div>
            <div id="field5-container" class="field f_100 clear">
                <label for="field5">
                    <?=$this->translate('L_HASHES_LOAD_LIST_DELIMITER')?>
                </label>
                <input type="text" name="delimiter" id="field5" required value=":">
            </div>
            <div id="field3-container" class="field f_100 clear">
                <label for="field3">
                    <?=$this->translate('L_HASHES_LOAD_LIST_FILE')?>
                </label>
                <div class="type_file">
                    <input type="file" name="file" size="28" class="inputFile" onchange='hashlistFileChange(this.value)' id="pairsForm_file"/>
                    <div class="fonTypeFile"><span><?=$this->translate('L_HASHES_LOAD_LIST_REVIEW')?></span></div>
                    <input type="text" class="inputFileVal" readonly id="fileName" placeholder="<?=$this->translate('L_HASHES_LOAD_LIST_NO_FILE')?>" />
                </div>
            </div>

            <!--div id="field2-container" class="field f_100 clear">
                <label for="field2">
                    тип списка
                </label>

                <div class="select clear">
                    <a href="#" class="slct">Значение не выбрано</a>
                    <ul class="drop">
                        <li>Значение 1</li>
                        <li>Значение 2</li>
                        <li>Значение 3</li>
                    </ul>
                    <input type="hidden" id="select" />
                </div>
            </div>

            <div id="field5-container" class="field f_100 clear">
                <label for="field5">
                    Текстовая строка
                </label>
                <input type="text" name="field5" id="field5" required>
            </div>

            <div id="field1-container" class="field f_100 clear">
                <label for="field1">
                    Текстовое поле
                </label>
                <textarea rows="5" cols="20" name="field1" id="field1" required placeholder=""></textarea>
            </div>

            <div id="field6-container" class="field f_100 clear">
                <div class="checkbox clear">
                    <div class="clear">
                        <input id="check1" type="checkbox" name="check" value="check1">
                        <label for="check1">Пассивный чек бокс</label>
                    </div>
                    <div class="clear">
                        <input id="check2" type="checkbox" name="check" value="check2">
                        <label for="check2">Наведенный чек бокс</label>
                    </div>
                    <div class="clear">
                        <input id="check3" type="checkbox" name="check" value="check3">
                        <label for="check3">Нажатый чек бокс</label>
                    </div>
                </div>
            </div-->

            <div id="form-submit" class="field f_100 clear">
                <input type="submit" value="<?=$this->translate('L_HASHES_LOAD_LIST_UPLOAD')?>" id="pairsForm_button">
            </div>
        </form>
    </div>
</div><!--------End Mobal--------->


