<li><a id="menu-servers" href="#server-openlist"><?=$this->translate('L_SERVERS')?> <sup>(<?=$this->serversCount?>)</sup></a></li>
<li><a id="menu-domains" href="#domain-openlist"><?=$this->translate('L_DOMAINS')?> <sup>(<?=$this->domainsCount?>)</sup> </a></li>
<li><a id="menu-webapps" href="#webapp-openlist"><?=$this->translate('L_WEB_APPS');?> <sup>(<?=$this->webAppsCount?>)</sup></a></li>
<li><a id="menu-spo" href="#spo-openlist"><?=$this->translate('L_SPO');?> <sup>(<?=$this->spoCount?>)</sup></a></li>
<li><a id="menu-vulns" href="#vuln-openlist"><?=$this->translate('L_VULNS')?> <sup>(<?=$this->vulnsCount?>)</sup></a></li>
<li><a id="menu-files" href="#file-openlist"><?=$this->translate('L_FILES')?> <sup>(<?=$this->filesCount?>)</sup></a></li>
<li><a id="menu-tasks" href="#task-openlist"><?=$this->translate('L_TASKS')?> <sup>(<?=$this->tasksCount?>)</sup></a></li>
<li><a id="menu-users" href="#user-openlist"><?=$this->translate('L_USERS')?> <sup>(<?=$this->usersCount?>)</sup></a></li>
<li><a id="menu-users" href="/visual/index/project_id/<?=$this->projectId?>" target="_blank"><?=$this->translate('L_VISUAL')?></a></li>