    <div class="clear info-block">
        <a href="/servers/index/project_id/<?=$this->project['id']?>" class="tittle"><?=$this->project['name']?></a>
        <p class="info"><?=nl2br(htmlspecialchars($this->project['comment']))?></p>
    </div>
    <div class="ico-block clear">
        <!--a class="icon-doc icon report" href="#report"><p>Отчет<span></span></p></a-->
        <a class="icon-edit icon change" href="#" id="projectEdit<?=$this->project['id']?>" onclick="openProjectEditForm(<?=$this->project['id']?>)"><p><?=$this->translate('L_CHANGE');?><span></span></p></a>
        <!--a class="icon-dload icon download" href="#"><p>Скачать<span></span></p></a-->
    </div>
    <a class="icon-cross icon close" id="projectDel<?=$this->project->id?>" onclick="projectDelete(<?=$this->project->id?>, '<?=$this->project->name?>')"></a>
