<div id="top-fix" class="clear">
    <form id="filterForm" action="" method="post">
        <div id="top-m" class="clear">
            <div class="left">
                <label><?=$this->translate('L_FILTER')?></label>
                <input id="filterSearch" name="search" value="" title="" type="text" />
                <img id="searchIcon" src="/images/zoom.png" class="searchIcon cursor" onclick="goTasksListLink(1);"/>
            </div>
            <div class="right">
                <a id="addTaskLink" href="#" data-type="" data-object="" class="button newicons2" title="<?=$this->translate('L_ADD_TASK')?>" onclick="openTaskAddForm($(this).data('type'), $(this).data('object'));return false;">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </a>
            </div>
        </div>
        <div id="middle" class="clear">
            <div>
                <label><?=$this->translate('L_TASK_TYPE')?></label>
                <select id="filterType" name="type" onchange="tasksFilterTypeChange(this.value);">
                    <option value="0">-------</option>
                    <option value="project"><?=$this->translate('L_PROJECT')?></option>
                    <option value="server"><?=$this->translate('L_SERVER')?></option>
                    <option value="domain"><?=$this->translate('L_DOMAIN')?></option>
                    <option value="web-app"><?=$this->translate('L_WEB_APPS');?></option>
                    <option value="server-software"><?=$this->translate('L_SPO');?></option>
                </select>
            </div>
            <div id="parentDiv">
                <label><?=$this->translate('L_PARENT')?></label>
                <select id="filterParent" name="parent" onchange="tasksFilterParentChange(this.value)">
                    <option value="0">-------</option>
                </select>
            </div>
            <div id="objectDiv">
                <label><?=$this->translate('L_OBJECT')?></label>
                <select id="filterObject" name="object_id" onchange="tasksFilterObjectChange(this.value);if (!app_navigation) {goTasksListLink(1)}">
                    <option value="0">-------</option>
                </select>
            </div>
        </div>
</div><!--End #top-fix-->

<div id="content">



</div><!--End #work-space #content-->

<script>
    function changePage(page) {
        tasksListFilter(page)
    }
    (function($){
        //tasksListFilter(1)
    })(jQuery);
</script>

