<form action="/files/add/" method="POST" id="fileAddForm" enctype="multipart/form-data">
    <?=$this->element->object_id?>
    <?=$this->element->type?>
    <table>
        <tr>
            <td><?=$this->element->file->getLabel()?></td>
            <td><?=$this->element->file?></td>
        </tr>
        <tr>
            <td colspan="2">
                <?=$this->element->comment->getLabel()?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <?=$this->element->comment?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <?=$this->element->button?>
            </td>
        </tr>
    </table>
</form>
