<div id="top-fix" class="clear">
    <form id="filterForm" action="" method="post">
        <div id="top-m" class="clear">
            <div class="left">
                <label><?=$this->translate('L_FILTER')?></label>
                <input id="filterSearch" name="search" value="" title="" type="text" />
                <img id="searchIcon" src="/images/zoom.png" class="searchIcon cursor" onclick="goDomainsListLink();"/>
            </div>
            <div class="right">
                <a id="exportListButton" href="#" class="button newicons2" data-server="" title="<?=$this->translate('L_EXPORT_LIST')?>" onclick="domainsListExport($(this).data('server'));return false;">
                    <i class="fa fa-download" aria-hidden="true"></i>
                </a>
            </div>
            <div class="right">
                <a id="importListButton" href="#" class="button newicons2" data-server="" title="<?=$this->translate('L_IMPORT_LIST')?>" onclick="openDomainsListImportForm($(this).data('server'));return false;">
                    <i class="fa fa-upload" aria-hidden="true"></i>
                </a>
            </div>
            <div class="right">
                <a id="addDomainLink" href="#" data-server="" class="button newicons2" title="<?=$this->translate('L_ADD_DOMAIN')?>" onclick="openDomainAddForm($(this).data('server'));return false;">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </a>
            </div>
        </div>
        <div id="middle" class="clear">
            <div>
                <label><?=$this->translate('L_SERVER')?></label>
                <select id="filterServer" name="server_id" onchange="setServerIdToLinks(this.value);;if (!app_navigation) {goDomainsListLink(1)}">
                    <option value="0">-------</option>
                    <?foreach ($this->servers as $server):?>
                        <option value="<?=$server['id']?>"><?=$server['name']?></option>
                    <?endforeach;?>
                </select>
            </div>
        </div>
</div><!--End #top-fix-->

<div id="content">



</div><!--End #work-space #content-->


<script>
    function changePage(page) {
        domainsListFilter(page)
    }

    (function($){
        //domainsListFilter(1)
    })(jQuery);
</script>
