<div id="top-fix" class="clear">
    <form id="filterForm" action="" method="post">
        <div id="top-m" class="clear">
            <div class="right">
                <a id="addTaskTemplateLink" href="#" data-type="" data-object="" class="button newicons2" title="<?=$this->translate('L_ADD_TASK_TEMPLATE')?>" onclick="openTaskTemplateAddForm($(this).data('type'));return false;">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </a>
            </div>
        </div>
        <div id="middle" class="clear">
            <div>
                <label><?=$this->translate('L_TASK_TYPE')?></label>
                <select id="filterType" name="type" onchange="tasksTemplatesFilterTypeChange(this.value);">
                    <option value="0">-------</option>
                    <option value="server"><?=$this->translate('L_SERVER')?></option>
                    <option value="domain"><?=$this->translate('L_DOMAIN')?></option>
                    <option value="web-app"><?=$this->translate('L_WEB_APPS');?></option>
                    <option value="server-software"><?=$this->translate('L_SPO');?></option>
                </select>
            </div>
        </div>
    </form>
</div><!--End #top-fix-->

<div id="content">



</div><!--End #work-space #content-->

<script>
    function changePage(page) {
        tasksListFilter(page)
    }
    (function($){
        //tasksListFilter(1)
    })(jQuery);
</script>

