<form action="/severs/edit/" method="POST" id="serverEditForm">
    <?=$this->element->id?>
    <?=$this->element->project_id?>
    <table>
        <tr>
            <td><?=$this->element->name->getLabel()?></td>
            <td><?=$this->element->name?></td>
        </tr>
        <tr>
            <td><?=$this->element->ip->getLabel()?></td>
            <td><?=$this->element->ip?></td>
        </tr>
        <tr>
            <td><?=$this->element->os_id->getLabel()?></td>
            <td><?=$this->element->os_id?></td>
        </tr>
        <tr>
            <td><?=$this->element->os_version->getLabel()?></td>
            <td><?=$this->element->os_version?></td>
        </tr>
        <tr>
            <td><?=$this->element->checked->getLabel()?></td>
            <td><?=$this->element->checked?></td>
        </tr>
        <tr>
            <td colspan="2">
                <?=$this->element->comment->getLabel()?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <?=$this->element->comment?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <?=$this->element->button?>
            </td>
        </tr>
    </table>
</form>