<form action="/users/pairs-load/" method="POST" id="pairsForm" enctype="multipart/form-data">
    <?=$this->element->group_id?>
    <table id="pairsFormTable">
        <tr>
            <td><?=$this->element->delimiter->getLabel()?></td>
            <td><?=$this->element->delimiter?></td>
        </tr>
        <tr>
            <td><?=$this->element->alg_id->getLabel()?></td>
            <td><?=$this->element->alg_id?></td>
        </tr>
        <tr>
            <td><?=$this->element->file->getLabel()?></td>
            <td><?=$this->element->file?></td>
        </tr>
        <tr>
            <td colspan="2"><?=$this->element->submit?></td>
        </tr>
    </table>
</form>