<style>
    #content {
        top: 20px;
    }
    #content .top-block{
        padding: 30px 40px;
    }
</style>
<div id="content">
    <div class="top-block clear">
        <h2> <?=$this->webApp['name']?> ( <?=$this->webApp['url']?> )
            <i class="icon-edit cursor" id="webAppEdit<?=$this->webApp['id']?>" onclick="openWebAppEditForm(<?=$this->webApp['id']?>)"></i>
        </h2>
        <p class="iconsViewBlock">

            <?if ($this->webApp['checked']):?>
                <span class="fa fa-check-circle serverCheckedIcon"  title="<?=$this->translate('L_CHECKED');?>"></span>
            <?endif?>
            <?if ($this->webApp['need_auth']):?>
                <span class="fa fa-key serverCheckedIcon"  title="<?=$this->translate('L_NEED_AUTH');?>"></span>
            <?endif?>
            <?if ($this->webApp['ghost']):?>
                <span class="fa fa-cloud serverCheckedIcon"  title="<?=$this->translate('L_GHOST');?>"></span>
            <?endif?>
            <?if ($this->webApp['url_rewrite']):?>
                <span class="fa fa-refresh serverCheckedIcon"  title="<?=$this->translate('L_URL_REWRITE');?>"></span>
            <?endif?>


        </p>
        <h3 class="m-t-20">Версия</h3>
        <p>
            <?if ($this->webApp['version']):?>
                <?if ($this->webApp['version_old']):?>
                    <font color="red" title="<?=$this->translate('L_OLD_VERSION');?>"><?=$this->webApp['version']?></font>
                <?else:?>
                    <font color="green" title="<?=$this->translate('L_LAST_VERSION');?>"><?=$this->webApp['version']?></font>
                <?endif?>

            <?else:?>
        <div title="<?=$this->translate('L_VERSION_UNKNOWN');?>">v.?</div>
        <?endif?>
        </p>
        <h3 class="m-t-20"><?=$this->translate('L_DEVELOPER')?></h3>
        <p><?=$this->webApp['vendor_site']?></p>

        <h3 class="m-t-20"><?=$this->translate('L_COMMENT')?></h3>
        <p><?=$this->webApp['comment']?></p>
        <br/>
        <a id="childUsers" href="#user-openlist-FILTER-web-app/<?=$this->domain['id']?>/<?=$this->webApp['id']?>/0"><?=$this->translate('L_USERS')?> (<?=$this->usersCount?>)</a>
        &nbsp;&nbsp;&nbsp;
        <a id="childVulns" href="#vuln-openlist-FILTER-web-app/<?=$this->domain['id']?>/<?=$this->webApp['id']?>"><?=$this->translate('L_VULNS')?> (<?=$this->vulnsCount?>)</a>
        &nbsp;&nbsp;&nbsp;
        <a id="childTasks" href="#task-openlist-FILTER-web-app/<?=$this->domain['id']?>/<?=$this->webApp['id']?>"><?=$this->translate('L_TASKS')?> (<?=$this->tasksCount?>)</a>
        &nbsp;&nbsp;&nbsp;
        <a id="childFiles" href="#file-openlist-FILTER-web-app/<?=$this->domain['id']?>/<?=$this->webApp['id']?>"><?=$this->translate('L_FILES')?> (<?=$this->filesCount?>)</a>
    </div><!--End .top-block-->
</div><!--End #content-->
